Repository Fusion-Power-Plant-Framework/eqdsk, pull requests merged in 2024-10, with the labels that each got.

#26 Added CLI, repr and plotting routines
  CONTRIBUTING.md
  README.md
  eqdsk/cli.py
  eqdsk/cocos.py
  eqdsk/file.py
  eqdsk/log.py
  eqdsk/tools.py
  pyproject.toml
  tests/test_data/DN-DEMO_eqref.json
  tests/test_data/DN-DEMO_eqref_withCoilNames.json
  tests/test_file.py
Labels: enhancement

#28 Getting docs right
  .github/workflows/main_and_pr.yml
  .github/workflows/publish-docs.yml
  docs/examples.md
  docs/examples/using_api.md
  docs/examples/using_cli.md
  docs/index.md
  docs/reference/cocos.py.md
  docs/reference/file.py.md
  eqdsk/__init__.py
  eqdsk/cli.py
  eqdsk/cocos.py
  eqdsk/file.py
  mkdocs.yml
  pyproject.toml
  scripts/gen_api_ref.py
Labels: documentation

#30 Acknowledgements
  ACKNOWLEDGEMENTS.md
  docs/index.md
  eqdsk/file.py
Labels: documentation

#29 Add precommit autoupdate
  .pre-commit-config.yaml
Labels: CI

#31 Spelling
  docs/examples/using_api.md
  docs/index.md
Labels: quality

#33 Make axes equal
  eqdsk/cli.py
Labels: enhancement
